### PR TITLE
Fix version check of the plugins SDK

### PR DESCRIPTION
**Pull request by rbetancor**
The SDK version check was not ok to compile agains 0.9.4+ versions

### CODE REVIEW

**Comment by ivmartel** [comment]
Got it but still want to keep 0.8.6 compatibility. See following commit.

**Comment by ivmartel** [comment]
Added multi-version compilation in travis at 30f5354, all builds!

**Comment by rbetancor** [comment]
It's the same, as the SDK changed on 0.9.5, so why to check if 0.8.6 OR minor OR equal to 0.9.4, that's the same as if minor to 0.9.5

**Comment by ivmartel** [comment]
For 0.8.6: (0 <= 0 && 8 <= 9 && 6 <= 4) -> FALSE
Which leads to this failure: https://travis-ci.org/ivmartel/dwv-orthanc-plugin/builds/95876940

**Comment by rbetancor** [comment]
Thats true, sorry. Maybe the check should be changed to a full string, as many other SDK's does ... duplicating the #define to something like ... #define ORTHANC_PLUGINS_NUMBER 095 ... that way the check will be simple and never fails

**Pull request closed without merging**
